{
	"version": 1546621574,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/grid.png",
		"images/plataformasolida.png",
		"images/plataformamovel.png",
		"images/spike.png",
		"images/key-sheet0.png",
		"images/door-sheet0.png",
		"images/door-sheet1.png",
		"images/door-sheet2.png",
		"images/player_icon-sheet0.png",
		"images/door_icon-sheet0.png",
		"images/door_icon-sheet1.png",
		"images/playeranimation-sheet0.png",
		"images/particles.png",
		"images/sprite-sheet0.png",
		"images/moeda-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/scoretext.png",
		"images/tiledbackground.png",
		"images/sprite2-sheet0.png",
		"images/inimigo-sheet0.png",
		"images/inimigo-sheet1.png",
		"images/sprite4-sheet0.png",
		"images/sprite4-sheet1.png",
		"images/bsom-sheet0.png",
		"images/bsom-sheet1.png",
		"images/sprite5-sheet0.png",
		"images/sprite5-sheet1.png",
		"media/sonic ring sound (online-audio-converter.com).m4a",
		"media/sonic ring sound (online-audio-converter.com).ogg",
		"media/mario power up sound effect (online-audio-converter.com).m4a",
		"media/mario power up sound effect (online-audio-converter.com).ogg",
		"media/mario_jumping-mike_koenig-989896458.m4a",
		"media/mario_jumping-mike_koenig-989896458.ogg",
		"media/undertale - megalovania (1) (online-audio-converter.com).m4a",
		"media/undertale - megalovania (1) (online-audio-converter.com).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}